packages:
  - packages/*
onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - keytar
  - node
minimumReleaseAgeExclude:
  - "@rifen/timescope-core@0.1.0 || 0.1.1"
overrides:
  serialize-javascript: ">=7.0.3"
